version: "3"

services:
  db:
    container_name: django_db
    image: postgres:11.2
  web:
    container_name: django_web
    build: .
    volumes:
      - .:/code
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - db
